services:
  postgres:
    image: "postgres:14.4-bullseye"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
    ports:
      - "5432:5432"
    stop_grace_period: "3s"
    volumes:
      - "postgres:/var/lib/postgresql/data"
  redis:
    image: "redis:7.0.2-bullseye"
    restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
    stop_grace_period: "3s"
    volumes:
      - "redis:/data"
    profiles: ["redis"]

volumes:
  postgres: {}
  redis: {}
